#!/usr/bin/env bash
# .claude/hooks/worktree_create.sh
#
# WorktreeCreate lifecycle hook.
#
# Executed by Claude Code when a new Git Worktree is created for a developer
# stream. Scans for a contiguous block of 5 free localhost ports starting
# from BASE_PORT + (WORKTREE_INDEX * 5) and writes them to an .env.local
# file inside the worktree directory.
#
# This eliminates EADDRINUSE collisions when 4 developer streams run
# simultaneous test suites, dev servers, and database daemons.
#
# Environment variables injected by Claude Code:
#   WORKTREE_PATH   - Absolute path to the newly created worktree directory
#   WORKTREE_NAME   - Short name/slug for the worktree (e.g. feat-auth-module)
#
# Overridable database credential variables (see .env.example):
#   PG_TEST_USER     - PostgreSQL test user (default: postgres)
#   PG_TEST_PASSWORD - PostgreSQL test password (default: postgres)
#
# Exit codes:
#   0 - Success
#   1 - WORKTREE_PATH not set or port scan failed

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

BASE_PORT=3000          # Port allocation starts here
BLOCK_SIZE=5            # 5 ports reserved per worktree
MAX_WORKTREES=8         # Maximum concurrent developer streams supported
LOCK_FILE="/tmp/.claude_port_lock"

# ---------------------------------------------------------------------------
# Validate environment
# ---------------------------------------------------------------------------

if [[ -z "${WORKTREE_PATH:-}" ]]; then
    echo "ERROR: WORKTREE_PATH is not set. Cannot allocate ports." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Port availability check
# ---------------------------------------------------------------------------

is_port_free() {
    local port=$1
    # Try lsof first (macOS/Linux), fall back to nc
    if command -v lsof &>/dev/null; then
        ! lsof -iTCP:"${port}" -sTCP:LISTEN -t &>/dev/null
    else
        ! nc -z 127.0.0.1 "${port}" 2>/dev/null
    fi
}

is_block_free() {
    local start=$1
    for ((i = 0; i < BLOCK_SIZE; i++)); do
        if ! is_port_free $((start + i)); then
            return 1
        fi
    done
    return 0
}

# ---------------------------------------------------------------------------
# Allocate a free port block (with lock to prevent race conditions)
# ---------------------------------------------------------------------------

(
    flock -x 200

    ALLOCATED_START=""

    for ((w = 0; w < MAX_WORKTREES; w++)); do
        candidate=$((BASE_PORT + w * BLOCK_SIZE))
        if is_block_free "${candidate}"; then
            ALLOCATED_START="${candidate}"
            break
        fi
    done

    if [[ -z "${ALLOCATED_START}" ]]; then
        echo "ERROR: No free port block found in range ${BASE_PORT}-$((BASE_PORT + MAX_WORKTREES * BLOCK_SIZE))" >&2
        exit 1
    fi

    # ---------------------------------------------------------------------------
    # Resolve database credentials — overridable via environment variables.
    # Defaults are development-only values; override in CI and staging via
    # PG_TEST_USER and PG_TEST_PASSWORD environment variables.
    # See .env.example for documentation.
    # ---------------------------------------------------------------------------

    PG_USER="${PG_TEST_USER:-postgres}"
    PG_PASS="${PG_TEST_PASSWORD:-postgres}"

    # ---------------------------------------------------------------------------
    # Write .env.local into the worktree
    # ---------------------------------------------------------------------------

    ENV_FILE="${WORKTREE_PATH}/.env.local"

    cat > "${ENV_FILE}" <<EOF
# Auto-generated by .claude/hooks/worktree_create.sh
# Worktree: ${WORKTREE_NAME:-unknown}
# DO NOT EDIT MANUALLY — regenerated on each worktree creation.
# Override PG_TEST_USER / PG_TEST_PASSWORD in your shell before running
# this hook to use non-default database credentials.

PORT_APP=${ALLOCATED_START}
PORT_API=$((ALLOCATED_START + 1))
PORT_DB=$((ALLOCATED_START + 2))
PORT_TEST=$((ALLOCATED_START + 3))
PORT_METRICS=$((ALLOCATED_START + 4))

# Convenience aliases
APP_URL=http://localhost:${ALLOCATED_START}
API_URL=http://localhost:$((ALLOCATED_START + 1))
DATABASE_URL=postgresql://${PG_USER}:${PG_PASS}@localhost:$((ALLOCATED_START + 2))/lore_eligibility_test
EOF

    echo "Port block allocated: ${ALLOCATED_START}-$((ALLOCATED_START + BLOCK_SIZE - 1)) → ${ENV_FILE}"

) 200>"${LOCK_FILE}"
